spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:test
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect