create table statistic (id bigint generated by default as identity, creation_date_time timestamp, file_name varchar(255), primary key (id));
create table statistic_map (statistic_id bigint not null, map bigint, map_key varchar(1023) not null, primary key (statistic_id, map_key));
alter table statistic_map add constraint FK_statistic_map foreign key (statistic_id) references statistic;